# Brewfile

# Make sure we have all the taps we need before beginning.
tap 'homebrew/cask-cask'
tap 'homebrew/cask-versions'

brew 'autojump'
brew 'coreutils'
brew 'couchdb'
brew 'fasd'
brew 'gifsicle'
brew 'git'
brew 'graphicsmagick'
brew 'imagemagick'
brew 'pngquant'
brew 'rbenv'
brew 'wifi-password'
brew 'wget'

# Casks
cask_args appdir: '/Applications'

cask 'alfred'
cask 'colorpicker-skalacolor'
cask 'docker'
cask 'dropbox'
cask 'epichrome'
cask 'firefox'
cask 'google-chrome'
cask 'imageoptim'
cask 'iterm2'
cask 'jetbrains-toolbox'
cask 'kap'
cask 'now'
cask 'openemu'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'quicklook-json'
cask 'sequel-pro'
cask 'sketch'
cask 'slack'
cask 'spotify'
cask 'steam'
cask 'sublime-text'
cask 'the-unarchiver'
cask 'transmission'
cask 'transmit'
cask 'tunnelblick'
cask 'visual-studio-code'
cask 'vlc'
